config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :attacks
  get 'pages/about'

  get 'pages/contact'

  root 'attacks#index'

end

app/models/attack.rb
class Attack < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attacks_controller.rb
class AttacksController < ApplicationController
  before_action :set_attack, only: [:show, :edit, :update, :destroy]

  # GET /attacks
  # GET /attacks.json
  def index
    @attacks = Attack.all
  end

  # GET /attacks/1
  # GET /attacks/1.json
  def show
  end

  # GET /attacks/new
  def new
    @attack = Attack.new
  end

  # GET /attacks/1/edit
  def edit
  end

  # POST /attacks
  # POST /attacks.json
  def create
    @attack = Attack.new(attack_params)

    respond_to do |format|
      if @attack.save
        format.html { redirect_to @attack, notice: 'Attack was successfully created.' }
        format.json { render :show, status: :created, location: @attack }
      else
        format.html { render :new }
        format.json { render json: @attack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attacks/1
  # PATCH/PUT /attacks/1.json
  def update
    respond_to do |format|
      if @attack.update(attack_params)
        format.html { redirect_to @attack, notice: 'Attack was successfully updated.' }
        format.json { render :show, status: :ok, location: @attack }
      else
        format.html { render :edit }
        format.json { render json: @attack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attacks/1
  # DELETE /attacks/1.json
  def destroy
    @attack.destroy
    respond_to do |format|
      format.html { redirect_to attacks_url, notice: 'Attack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attack
      @attack = Attack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attack_params
      params.require(:attack).permit(:status, :case_id, :client, :attack_type, :url, :detection_time, :detection_method, :notes)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attacks_helper.rb
module AttacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/attacks/_form.html.erb
<%= form_for(@attack) do |f| %>
  <% if @attack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attack.errors.count, "error") %> prohibited this attack from being saved:</h2>

      <ul>
      <% @attack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Attack" %> <%= f.label :"Status" %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :"Case" %> <%= f.label :"ID", style:"text-transform: uppercase" %><br>
    <%= f.text_field :case_id %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :attack_type %><br>
    <%= f.text_field :attack_type %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :detection_time %><br>
    <%= f.text_field :detection_time %>
  </div>
  <div class="field">
    <%= f.label :detection_method %><br>
    <%= f.text_field :detection_method %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attacks/edit.html.erb
<h1>Editing Attack</h1>

<%= render 'form' %>

<%= link_to 'Show', @attack %> |
<%= link_to 'Back', attacks_path %>

app/views/attacks/index.html.erb
<style>
  .uRl {
    overflow: hidden;
  }
  .uRl:hover {
    overflow: auto;
  }
</style>

<p id="notice"><%= notice %></p>

<h1 align="center">Attacks Log</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Attack Status</th>
      <th>Case ID</th>
      <th>Client</th>
      <th>Attack type</th>
      <th align="center"><div align="center" style="width:100%; overflow:auto">Url</div></th>
      <th>Detection Time</th>
      <th>Detection Method</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attacks.each do |attack| %>
      <tr>
        <td><%= attack.status %></td>
        <td><%= attack.case_id %></td>
        <td><%= attack.client %></td>
        <td><%= attack.attack_type %></td>
        <td align="center"><div class="uRl" align="center" style="width:75%"><%= attack.url %></div></td>
        <td><%= attack.detection_time %></td>
        <td><%= attack.detection_method %></td>
        <td><%= attack.notes %></td>
        <td><%= link_to 'Show', attack %></td>
        <td><%= link_to 'Edit', edit_attack_path(attack) %></td>
        <td><%= link_to 'Destroy', attack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attack', new_attack_path %>

app/views/attacks/new.html.erb
<h1>New Attack</h1>

<%= render 'form' %>

<%= link_to 'Back', attacks_path %>

app/views/attacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @attack.status %>
</p>

<p>
  <strong>Case ID:</strong>
  <%= @attack.case_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @attack.client %>
</p>

<p>
  <strong>Attack type:</strong>
  <%= @attack.attack_type %>
</p>

<p>
  <strong>Url:</strong>
  <%= @attack.url %>
</p>

<p>
  <strong>Detection time:</strong>
  <%= @attack.detection_time %>
</p>

<p>
  <strong>Detection method:</strong>
  <%= @attack.detection_method %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @attack.notes %>
</p>

<%= link_to 'Edit', edit_attack_path(@attack) %> |
<%= link_to 'Back', attacks_path %>

app/views/layouts/_bootstrap.html.erb
<!--Bootstrap code below -->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<!--Bootstrap code above -->

app/views/layouts/_footer.html.erb
<div align="center">
	Copyright Nate Dunning & Nick Schumacher
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand pull-left" href="/attacks" style="width: 150px">
        <img src="/images/centurion_1.png" style="height:40px; margin-top: -8px" class="pull-left">Centurion
      </a>
      <%#= link_to "Centurion", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phase1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<!-- Bootstrap partial -->
 	<%= render 'layouts/bootstrap' %>

</head>
<body>
	<%= render 'layouts/navbar' %>

	<!--<p class="notice"><%#= notice %></p>
    <p class="alert"><%#= alert %></p>-->

	<div class="container-fluid">
		<%= yield %>
	</div>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>